spring:
  application:
    name: kotlin-crud
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2.file:~/test
      username: sa
      password: p@ssw0rd!@#
      driverClassName: org.h2.Driver
      schema: classpath:sql/schema.sql